### PR TITLE
Localhost access log

### PR DESCRIPTION
**Pull request by isuftin**
Updates to allow better definition of the localhost access log valve

### CODE REVIEW

**Comment by isuftin** [comment]
@mamcderm-usgs Let me know what you think of this

**Comment by mamcderm-usgs** [comment]
@isuftin - This looks good to me, the access logging should be helpful.  I just merged my PR and realized I did not update the cookbook version.  Do you want to update the version on this PR and tag/upload?  I'm planning to test the other PR on Traina1 instance, so I could check this as well.  Or let me know if you want to handle another way.

**Comment by isuftin** [comment]
@mamcderm-usgs Let's tag the next version once all PRs are in and tested

**Comment by mamcderm-usgs** [comment]
@isuftin - I'm not clear how the workflow should go.  I can change the version locally and upload to Chef, without tagging.  So, for example, we would have 1.0.5 on the server and the latest github tag would be 1.0.4.  If no problems, we would tag the the head in github to be 1.0.5.  If we have problems and need to make a change, I would have to increase the version locally to 1.0.6 and upload to Chef, correct?  Then if that was good, we would tag the head 1.0.6 and have a "missing" tagged version in github.  Or are you saying to upload the change with a `force` to 1.0.5 on the server to keep the cookbook version and tags in sync?  I thought you had previously said not to force an upload?  Am I missing something about how best to keep the tag and cookbook version in sync without always having to increase the cookbook version for changes going to the server?

**Comment by isuftin** [comment]
@mamcderm-usgs I'd tag it locally @ 1.0.5. I'd check out that tag locally and upload to Chef to test. Once that test goes fine, tag it remotely in GitHub. If things don't go well, delete the 1.0.5 cookbook from Chef and delete your tag locally. Only push the tag to GitHub once all tests go fine.

This is a special case because you do want to test on a remote server that hooks up to our central Chef server. I typically don't do this as my local tests via test kitchen have a good prediction rate as to how the cookbook run will go 'in the wild'.

If you do still want to test this in our working environment in AWS, I'd suggest making sure all nodes that use the Tomcat cookbook have their tomcat cookbooks version locked to 1.0.4 in their environment definitions.

**Comment by mamcderm-usgs** [comment]
@isuftin - When you say to tag it locally and check out that tag locally and upload to Chef to test, what do you mean to "check out that tag locally"?  I don't see any option for `git checkout` that uses tags?  Also, if I'm sitting in the cookbook directory locally and do `knife cookbook upload wsi-tomcat`, isn't that the same thing?  I guess I'm not understanding what tagging locally does at this point.  Also, I guess I missed the alternative of deleting a cookbook version and re-adding with changes.  Is that really different than uploading the same cookbook version with a `force` option?

So, if I'm going to test this cookbook version, I HAVE to version lock all the other instances using wsi-tomcat, right, or else risk affecting those apps/instances?  That's kind of a pain...but not seeing any other option?  This probably gets back to an overall topic of "SDLC for infrastructure as code", but that's for another time.  I guess I don't see this as a special case, though.  It seems like there are too many potential differences between test kitchen and the real environment...but it is subjective...

**Comment by mamcderm-usgs** [comment]
@isuftin - ok to merge this pull request?

**Comment by mamcderm-usgs** [comment]
@isuftin - Any idea why the cida-auth environments have version 0.2.4 for wsi_tomcat:

  "name": "owi-VPC-cida-auth-development",
  "description": "CIDA Auth Development",
  "cookbook_versions": {
    "stig": "= 0.6.10",
    "wsi_tomcat": "= 0.2.4",
    "cida-auth": "= 0.2.5",
    "java": "= 1.46.0",
    "sysctl": "= 0.9.0"
  },

Is that just a mistake or am I not understanding something else:-/

**Comment by isuftin** [comment]
@mamcderm-usgs Let's keep internal environment values out of public repositories, including the comments section.

You can check out a tag by using `git checkout <tag name>` as you would any branch. Tagging locally ensures that you are uploading the same version of the cookbook to the Chef server as it would be in GitHub at that specific tag. Its a formality that ensures stability down the line.

I don't use knife to upload my cookbooks, through Berkshelf should be able to do it for you.

Feel free to merge this if you feel it's good to go. Tag it in GitHub once it's been tested.

The application you're referring to with that environment simply runs an older version of Tomcat cookbook. Not necessarily a mistake.

**Pull request merged**
